apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - |
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: cert-manager
      namespace: cert-manager
    spec:
      chart:
        spec:
          version: "1.18.0"  # Use the version from vars