apiVersion: v1
kind: Namespace
metadata:
  name: observability-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: observability-system
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.47.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry-repo
        namespace: observability-system
  install:
    createNamespace: true
    remediation:
      retries: 3  # Retries in case of transient errors
  upgrade:
    remediation:
      retries: 3
  timeout: 10m
  values: {} # Add custom values here if needed
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: open-telemetry-repo
  namespace: observability-system
spec:
  interval: 5m
  url: https://open-telemetry.github.io/opentelemetry-helm-charts