apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - |
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: dynatrace-operator
      namespace: dynatrace
    spec:
      chart:
        spec:
          version: "1.4.0"  # Use the version from vars
configMapGenerator:
  - name: dynatrace-values
    namespace: dynatrace
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - cloudnativefullstack.yaml