apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - |
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: akv2k8s
      namespace: akv2k8s
    spec:
      chart:
        spec:
          version: "2.7.2"  # Use the version from vars
configMapGenerator:
  - name: akv2k8s-values
    namespace: akv2k8s
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml