apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-basic
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-basic
        namespace: ingress-basic
      version: 4.10.0
  valuesFrom:
    - kind: ConfigMap
      name: nginx-values
  values:
    controller:
      extraArgs:
        v: 3
  interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx-basic
  namespace: ingress-basic
spec:
  interval: 1m
  url: https://kubernetes.github.io/ingress-nginx
  
  

