apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - |
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: logstash
      namespace: logs
    spec:
      chart:
        spec:
          version: "8.5.1"  # Use the version from vars
configMapGenerator:
  - name: logstash-values
    namespace: logs
    files:
      - values.yaml
    options:
      labels:
        app: logstash
configurations:
  - kustomizeconfig.yaml