apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - |
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: opentelemetry-operator
      namespace: observability-system
    spec:
      chart:
        spec:
          version: "0.69.0"  # Use the version from vars
      values:
        manager:
          collectorImage:
            repository: "otel/opentelemetry-collector"