apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - |
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: ingress-nginx
      namespace: ingress-basic
    spec:
      chart:
        spec:
          version: "4.12.3"  # Use the version from vars
configMapGenerator:
  - name: nginx-values
    namespace: ingress-basic
    files:
      - values.yaml=ingress-nginx.yaml
configurations:
  - kustomizeconfig.yaml