apiVersion: v1
kind: Namespace
metadata:
  name: dynatrace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dynatrace-operator
  namespace: dynatrace
spec:
  releaseName: dynatrace-operator
  chart:
    spec:
      chart: dynatrace-operator
      sourceRef:
        kind: HelmRepository
        name: dynatrace
        namespace: dynatrace
      version: "0.13.0"  # Version for dev environment
  valuesFrom:
    - kind: ConfigMap
      name: dynatrace-values
  interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: dynatrace
  namespace: dynatrace
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/main/config/helm/repos/stable

  
  

