apiVersion: v1
kind: Namespace
metadata:
  name: logs
  labels:
    azure-key-vault-env-injection: enabled
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: logs
spec:
  interval: 10m
  chart:
    spec:
      chart: logstash
      sourceRef:
        kind: HelmRepository
        name: logstash
        namespace: logs
      version: "7.16.2"  # Replace with the desired version
  valuesFrom:
    - kind: ConfigMap
      name: logstash-values
      valuesKey: values.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: logstash
  namespace: logs
spec:
  interval: 10m
  url: https://helm.elastic.co