apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - |
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: ingress-nginx-public
      namespace: ingress-public
    spec:
      chart:
        spec:
          version: "4.12.1"  # Use the version from vars
configMapGenerator:
  - name: ingress-nginx-public
    namespace: ingress-public
    files:
      - values.yaml=ingress-nginx-public.yaml
configurations:
  - kustomizeconfig.yaml