apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 1m
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: keda
      version: "2.13.1"  # Replace with the desired version
  values: {}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: keda
  namespace: keda
spec:
  interval: 1m
  url: https://kedacore.github.io/charts